In [2]:
import numpy as np

### ReLU

In [3]:
def relu(x):
    # return np.where(x>0, x, 0)
    
    return np.maximum(x, 0)

In [4]:
x = np.array([1, -2])
inputs = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

In [5]:
from linear_forward import Linear
fc1 = Linear(2, 5)
fc2 = Linear(3, 2, random_state=20)
out1 = fc1(x)
out2 = fc2(inputs)

In [6]:
print(out1)
print(out2)

[ 0.30982506 -2.86410093  0.47608281 -1.86893689 -3.27951231]
[[  3.28770205  -3.81231925]
 [  7.59958601 -12.41751386]
 [ 11.91146996 -21.02270848]]


In [7]:
print(relu(out1))
print(relu(out2))

[0.30982506 0.         0.47608281 0.         0.        ]
[[ 3.28770205  0.        ]
 [ 7.59958601  0.        ]
 [11.91146996  0.        ]]


### Sigmoid

In [8]:
def sigmoid(x):
    
    return 1/(1 + np.exp(-x))

In [9]:
print(sigmoid(out1))
print(sigmoid(out2))

[0.57684256 0.05395698 0.61682246 0.13366478 0.03628076]
[[9.64004501e-01 2.16191555e-02]
 [9.99499592e-01 4.04706791e-06]
 [9.99993287e-01 7.41231239e-10]]


### Softmax

In [12]:
def softmax(x):
    if len(x.shape)==1:
        num = np.exp(x)
        den = np.sum(np.exp(x))
        
        return num/den
    
    exp = np.exp(x - np.max(x, axis=1, keepdims=True)) # adding numerical stability
    den = np.sum(exp, axis=1, keepdims=True)
    
    return exp/den

print(softmax(out1))
print(softmax(out2))

[0.42309871 0.01770203 0.49962772 0.04788698 0.01168456]
[[9.99175593e-01 8.24407134e-04]
 [9.99999998e-01 2.02620779e-09]
 [1.00000000e+00 4.97585872e-15]]
