In [1]:
import numpy as np

In [23]:
def neuron(inputs, random_state=42):
    np.random.seed(random_state)
    weights = np.random.rand(len(inputs))
    bias = np.random.rand(1)
    
    forward = np.dot(inputs, weights) + bias
    
    # forward2 = 0
    # for i in range(len(inputs)):
    #     forward2 += weights[i] * inputs[i]
    
    # forward2+=bias
    
    return forward

In [24]:
inputs = [1, 2, 3, 4]
neuron(inputs)

array([7.02260313])

In [25]:
def layer(inputs, num_neurons):
    outs = []
    for i in range(num_neurons):
        outs.append(neuron(inputs, random_state=i).item())
    
    return np.array(outs)

layer(inputs, 3)

array([6.3906699 , 3.2141003 , 4.29849217])

## Optimizing Layer

In [28]:
def layer(inputs, num_neurons, random_state=42):
    np.random.seed(random_state)
    weights = np.random.random((num_neurons, len(inputs)))
    bias = np.random.random(num_neurons)
    
    outs = np.dot(weights, inputs) + bias
    
    return outs

In [29]:
layer(inputs=inputs, num_neurons=3)

array([7.69902713, 4.31930221, 6.14047803])

## For Batch of data

In [41]:
inputs = [[1, 2, 3, 4, 5],
          [3, 4, 5, 6, 7],
          [5, 6, 7, 8, 9]]

inputs = np.array(inputs)

In [60]:
w = np.random.random((4, len(inputs[0])))
b = np.random.random(4)
x = np.dot(inputs, w.T)
x

array([[ 9.72421484,  3.22680102,  6.56642243,  6.85015598],
       [15.56899447,  5.91400292,  9.9713876 , 11.06927495],
       [21.41377411,  8.60120482, 13.37635278, 15.28839391]])

In [61]:
b

array([0.3978556 , 0.96947043, 0.86550713, 0.81707207])

In [62]:
x+b

array([[10.12207044,  4.19627145,  7.43192956,  7.66722806],
       [15.96685007,  6.88347336, 10.83689473, 11.88634702],
       [21.81162971,  9.57067526, 14.2418599 , 16.10546598]])

In [63]:
def batch_layer(inputs, num_neurons, random_state=42):
    np.random.seed(random_state)
    weights = np.random.random((num_neurons, len(inputs[0])))
    bias = np.random.random(num_neurons)
    
    outs = np.dot(inputs, weights.T) + bias
    
    return outs

batch_layer(inputs, num_neurons=7)

array([[ 8.45507504,  9.12012689,  6.31388551,  6.23431709,  5.95322435,
         5.45117541, 10.2626271 ],
       [14.07892603, 13.89901062, 10.74808764,  9.70547178,  9.68507081,
         9.72707374, 15.77790338],
       [19.70277701, 18.67789436, 15.18228977, 13.17662647, 13.41691728,
        14.00297207, 21.29317966]])