In [1]:
import numpy as np

In [2]:
def neuron(inputs, random_state=42):
    np.random.seed(random_state)
    weights = np.random.rand(len(inputs))
    bias = np.random.rand(1)
    
    forward = np.dot(inputs, weights) + bias
    
    # forward2 = 0
    # for i in range(len(inputs)):
    #     forward2 += weights[i] * inputs[i]
    
    # forward2+=bias
    
    return forward

In [3]:
inputs = [1, 2, 3, 4]
neuron(inputs)

array([7.02260313])

In [4]:
def layer(inputs, num_neurons):
    outs = []
    for i in range(num_neurons):
        outs.append(neuron(inputs, random_state=i).item())
    
    return np.array(outs)

layer(inputs, 3)

array([6.3906699 , 3.2141003 , 4.29849217])

## Optimizing Layer

In [5]:
def layer(inputs, num_neurons, random_state=42):
    np.random.seed(random_state)
    weights = np.random.random((num_neurons, len(inputs)))
    bias = np.random.random(num_neurons)
    
    outs = np.dot(weights, inputs) + bias
    
    return outs

In [6]:
layer(inputs=inputs, num_neurons=3)

array([7.69902713, 4.31930221, 6.14047803])

## For Batch of data

In [7]:
inputs = [[1, 2, 3, 4, 5],
          [3, 4, 5, 6, 7],
          [5, 6, 7, 8, 9]]

inputs = np.array(inputs)

In [8]:
w = np.random.random((4, len(inputs[0])))
b = np.random.random(4)
x = np.dot(inputs, w.T)
x

array([[ 5.55008407,  5.51307186,  5.32913718,  9.76745019],
       [ 9.02123875,  9.24491832,  9.60503551, 15.28272647],
       [12.49239344, 12.97676478, 13.88093383, 20.79800275]])

In [9]:
b

array([0.80839735, 0.30461377, 0.09767211, 0.68423303])

In [10]:
x+b

array([[ 6.35848141,  5.81768563,  5.42680929, 10.45168322],
       [ 9.8296361 ,  9.54953209,  9.70270762, 15.9669595 ],
       [13.30079079, 13.28137855, 13.97860595, 21.48223577]])

In [13]:
def batch_layer(inputs, num_neurons, random_state=42):
    np.random.seed(random_state)
    weights = np.random.random((num_neurons, len(inputs[0])))
    bias = np.random.random(num_neurons)
    
    outs = np.dot(inputs, weights.T) + bias
    
    return outs

batch_layer(inputs, num_neurons=7).shape

(3, 7)

## Stacking Layers

In [27]:
def forward_mlp(inputs, num_layers, neurons_in_layers, batched=False, random_state=42):
    inputs = np.array(inputs)
    assert num_layers == len(neurons_in_layers), "The neurons in layers should be equal to the number of layers"
    print(inputs.shape)
    # to handle batched inputs
    if batched:
        outs = batch_layer(inputs, neurons_in_layers[0], random_state=random_state)
        print(outs.shape)
        for i in range(1, num_layers):
            outs = batch_layer(outs, neurons_in_layers[i], random_state=i)
            print(outs.shape)
            
    # to handle single inputs
    else:
        outs = layer(inputs, neurons_in_layers[0], random_state=random_state)
        print(outs.shape)
        for i in range(1, num_layers):
            outs = layer(outs, neurons_in_layers[i], random_state=i)
            print(outs.shape)
    
    
    return outs

In [28]:
forward_mlp(inputs, 3, [4, 6, 2], batched=True)

(3, 5)
(3, 4)
(3, 6)
(3, 2)


array([[31.8447584 , 33.51619007],
       [50.20419367, 52.51219789],
       [68.56362894, 71.50820572]])

In [29]:
linear_inputs = [1, 2, 3, 4]

In [30]:
forward_mlp(linear_inputs, 4, [6, 7, 8, 2])

(4,)
(6,)
(7,)
(8,)
(2,)


array([178.82156503, 136.82566075])