In [1]:
import numpy as np
import random

In [75]:
class Neuron:
    def __init__(self, input_size, random_state=42):
        np.random.seed(42)
        if isinstance(input_size, int):
            self.weights = np.random.rand(input_size)
        else:
            self.weights = np.random.rand(input_size[-1])
        self.bias = np.random.random(1)
    
    def relu(self, x):
        return np.where(x>0, x, 0)
    
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def forward(self, inputs):
        out = np.dot(inputs, self.weights) + self.bias
        # return self.sigmoid(out)
        return self.relu(out)

In [76]:
inputs = np.random.rand(4)
inputs

array([0.12203823, 0.49517691, 0.03438852, 0.9093204 ])

In [79]:
n = Neuron(4)
n.forward(inputs)

array([1.24204319])

In [88]:
inputs = np.random.rand(2, 3)
n = Neuron((2, 3))
n.forward(inputs)

array([0.8479168 , 2.01286968])