In [1]:
import numpy as np
import random

In [2]:
class Neuron:
    def __init__(self, input_size, random_state=42):
        np.random.seed(42)
        if isinstance(input_size, int):
            self.weights = np.random.rand(input_size)
        else:
            self.weights = np.random.rand(input_size[-1])
        self.bias = np.random.random(1)
    
    def relu(self, x):
        return np.maximum(0, x)
    
    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))
    
    def forward(self, inputs):
        out = np.dot(inputs, self.weights) + self.bias
        # return self.sigmoid(out)
        return self.relu(out)

In [3]:
inputs = np.random.rand(4)
inputs

array([0.61181724, 0.68612334, 0.45910522, 0.29625495])

In [4]:
n = Neuron(4)
n.forward(inputs)

array([1.55089379])

In [5]:
inputs = np.random.rand(2, 3)
n = Neuron((2, 3))
n.forward(inputs)

array([1.3463413 , 1.51204263])